#
#  Copyright 2019 Square Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

site_name: Square Workflow
repo_name: Workflow
repo_url: https://github.com/square/workflow
site_description: "A library for making composable state machines, and UIs driven by those state machines."
site_author: Square, Inc.
site_url: https://square.github.io/workflow/
remote_branch: gh-pages
edit_uri: edit/main/docs/

copyright: 'Copyright &copy; 2019 Square, Inc.'

theme:
  name: 'material'
  logo: images/icon-square.png
  favicon: images/icon-square.png
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: 'red'
    accent: 'pink'
  features:
    - tabs
    - instant

extra_css:
  - 'css/app.css'

markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: True
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - tables

plugins:
  - search
  - redirects:
      redirect_maps:
        # Redirect some of the most-visited pages from their old locations in case there are links
        # to these pages somewhere.
        'kotlin/api/workflow-core/com.squareup.workflow/index.md': 'kotlin/api/htmlMultiModule/index.html'
        'kotlin/api/workflow-core/com.squareup.workflow/-worker/index.md': 'kotlin/api/htmlMultiModule/workflow-core/com.squareup.workflow1/-worker/index.html'
        'kotlin/api/workflow-testing/com.squareup.workflow.testing/index.md': 'kotlin/api/htmlMultiModule/workflow-testing/com.squareup.workflow1.testing/index.html'
        'kotlin/api/workflow-testing/com.squareup.workflow.testing/-render-tester/index.md': 'kotlin/api/htmlMultiModule/workflow-testing/com.squareup.workflow1.testing/-render-tester/index.html'

extra:
  # type is the name of the FontAwesome icon without the fa- prefix.
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/square
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squareeng
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/joinsquare/

nav:
  - 'Overview': index.md
  - 'Why Workflow?': 'userguide/whyworkflow.md'
  - 'User Guide':
    - 'Workflow Core': 'userguide/concepts.md'
    - 'Coding a Workflow (stale)': 'userguide/workflow-in-code.md'
    - 'Coding a Worker (stale)': 'userguide/worker-in-code.md'
    - 'Workflow UI (in progress)': 'userguide/ui-concepts.md'
    - 'Coding Workflow UI (in progress)': 'userguide/ui-in-code.md'
    - 'Testing (TBD)': 'userguide/testing-concepts.md'
    - 'Common Patterns': 'userguide/common-patterns.md'
    - 'Implementation Notes': 'userguide/implementation.md'
  - 'Tutorials and Samples':
    - 'Swift Tutorial 🔗': https://github.com/square/workflow-swift/tree/main/Samples/Tutorial
    - 'Swift Samples 🔗': https://github.com/square/workflow-swift/tree/main/Samples
    - 'Kotlin Tutorial 🔗': https://github.com/square/workflow-kotlin/tree/main/samples/tutorial#readme
    - 'Kotlin Samples 🔗': https://github.com/square/workflow-kotlin/tree/main/samples
  - 'API Reference':
    - 'Kotlin 🔗': 'kotlin/api/htmlMultiModule'
    - 'Swift 🔗': https://square.github.io/workflow-swift/documentation
  - 'Glossary': 'glossary.md'
  - 'FAQ': faq.md
  - 'Pre-1.0 Resources': historical.md
  - 'Changelog': CHANGELOG.md
  - 'Contributing': CONTRIBUTING.md
  - 'Code of Conduct': CODE_OF_CONDUCT.md

# Google Analytics. Add export WORKFLOW_GOOGLE_ANALYTICS_KEY="UA-XXXXXXXXX-X" to your ~/.bashrc
google_analytics:
  - !!python/object/apply:os.getenv ["WORKFLOW_GOOGLE_ANALYTICS_KEY"]
  - auto
