name: Validate documentation site

on:
  pull_request:
    paths:
      # Rebuild when workflow configs change.
      - .github/workflows/validate-documentation.yml
      # Or when documentation code changes.
      - 'docs/**'
      - '**.md'
      - mkdocs.yml
      - lint_docs.sh
      - .markdownlint.rb

jobs:
  mkdocs:
    name: Build mkdocs to validate mkdocs.yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run mkdocs
        run: mkdocs build

  lint:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.4.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
      - name: Install dependencies
        run: gem install mdl -v 0.13.0
      - name: Lint docs
        run: ./lint_docs.sh
